### PR TITLE
Tictactoe engine basic

### PR DESCRIPTION
**Pull request by adiman9**
Here is the modular code. Let me know what you think.

The algorithm is exactly as you created it, but I refactored some parts to either remove redundancy or to abstract implementation. The main refactor was the checkWin and tCheckWin methods. Both of these where almost identical and thus there was a lot of redundant code. I refactored the code so there is now only a single checkWin method that accepts a boolean argument that specifies if the check is a final check or a temp check.

I also made the checks more general so the case for a 3x3 and 4x4 grids can be checked by the same code, rather than having separate checks.

I hope this is all ok.

### CODE REVIEW

**Review by vijeth-aradhya — CHANGES_REQUESTED** [review]
I noticed that the "Choose number of players" button is not working. Can you please look into it?

**Comment by vijeth-aradhya** [comment]
@adiman9 When I checked, the "Choose number of players" was not working?

tic2

**Comment by adiman9** [comment]
It works for me. What errors are in the console?

**Comment by adiman9** [comment]
I recreated the issue. It was because I was assigning each function to a variable and the function wasn't being hoisted correctly.

I have fixed it now

**Comment by vijeth-aradhya** [comment]
@adiman9 Thank you so much for contributing!

**Pull request merged**
